name: build
on: 
  workflow_dispatch:
    inputs:
      a:
        type: string
        default: '[ {"a":"a1"}, {"a", "a2"} ]'
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        includes: >-
          ${{ fromJSON(inputs.a) }}
    steps:
      - run: echo "${{matrix.a}}" 
  
