name: build
on: 
  workflow_dispatch:
    inputs:
      myinput:
        type: string
        default: '{"a":[1,2]}'

jobs:

  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.myinput) }}
       
    steps:
      - run: echo "${{ matrix.a }}"
  
